name: m7_livelyness_detection
description: A single function package to detect weather the face visible in the camera is a live face or not.
version: 0.0.6+4
homepage: https://github.com/Meet-7-dating/m7_livelyness_detection
repository: https://github.com/Meet-7-dating/m7_livelyness_detection/
issue_tracker: https://github.com/Meet-7-dating/m7_livelyness_detection/issues

environment:
  sdk: '>=2.18.6 <3.0.0'
  flutter: ">=2.5.0"

dependencies:
  animate_do: 
  camera: 
  collection: 
  equatable:
  flutter:
    sdk: flutter
  google_mlkit_face_detection: 
  image: 
  lottie: 
  plugin_platform_interface: 

  rxdart: ^0.27.7
  camerawesome: ^1.4.0
  uuid: ^3.0.7



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.example.m7_livelyness_detection
        pluginClass: M7LivelynessDetectionPlugin
      ios:
        pluginClass: M7LivelynessDetectionPlugin

  # To add assets to your plugin package, add an assets section, like this:
  assets:
    - packages/m7_livelyness_detection/src/assets/lottie/livelyness-start.json
    - packages/m7_livelyness_detection/src/assets/lottie/livelyness-success.json
    - packages/m7_livelyness_detection/src/assets/lottie/step_completed.json
    - packages/m7_livelyness_detection/src/assets/final-mesh.png