name: m7_livelyness_detection
description: A single function package to detect weather the face visible in the camera is a live face or not.
version: 0.0.8+8
homepage: https://github.com/Meet-7-dating/m7_livelyness_detection
repository: https://github.com/Meet-7-dating/m7_livelyness_detection/
issue_tracker: https://github.com/Meet-7-dating/m7_livelyness_detection/issues

environment:
  sdk: '>=2.18.6 <4.0.0'
  flutter: ">=2.5.0"

dependencies:
  animate_do: 
  camera: 
  collection: 
  equatable:
  flutter:
    sdk: flutter
  google_mlkit_face_detection: ^0.12.0
  image: ^4.0.15
  lottie: ^3.1.3
  path_provider: ^2.0.14
  plugin_platform_interface: ^2.1.3
  rxdart: ^0.28.0
  camerawesome: ^2.1.0
  uuid: ^4.5.1



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  # To add assets to your plugin package, add an assets section, like this:
  assets:
    - packages/m7_livelyness_detection/src/assets/lottie/livelyness-start.json
    - packages/m7_livelyness_detection/src/assets/lottie/livelyness-success.json
    - packages/m7_livelyness_detection/src/assets/lottie/step_completed.json
    - packages/m7_livelyness_detection/src/assets/final-mesh.png